name: SonarQube Scan

on:
  # push:
  #   branches:
  #     - main
  pull_request:

jobs:
  sonar-scan:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up JDK (SonarScanner requires Java)
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'

    # Run SonarQube Scan
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v4
      with:
        args: >
          -Dsonar.projectKey=shivam2003-dev_CipherIntellect_ed85b78d-4270-4cc6-a731-7793bf79496b
          -Dsonar.sources=.
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Djavax.net.ssl.trustAll=true
